name = "GenericInstruments"
uuid = "b8d24480-b8ee-42fe-a917-db159b4b1a29"
authors = ["iuliancioarca"]
version = "0.1.0"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
